### PR TITLE
Added Chafu

### PR DESCRIPTION
**Pull request by Cheesebaron**
Added Chafu photo library and camera

### CODE REVIEW

**Comment by MarcBruins** [comment]
Awesome Cheesebaron!

**Comment by MarcBruins** [comment]
That's a neat little trick with the [ios] btw 👍

**Comment by Cheesebaron** [comment]
I can make a PR which fixes this for all of the images.

**Comment by MarcBruins** [comment]
That would be great! I'll replace all the current images with the tags then 👍

**Pull request merged**
